services:
  - type: web
    name: my-zegocloud-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: vite preview --port $PORT
    envVars:
      - key: PORT
        value: 10000